core/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('home.urls')),
    path("admin/", admin.site.urls),
    path("", include('admin_argon.urls'))
]

election/urls.py
from django.urls import include, path
from . import views

urlpatterns = [
    # path('get_user_organizations/', views.load_organizations, name='load_organizations'),
    path('load_units/', views.load_units, name='load_units'),
    path('organization/', views.organization_list, name='organization_list'),
    path('organization/create/', views.create_organization, name='create_organization'),
    path('organization/join/<int:organization_id>', views.join_organization, name='join_organization'),
    path('organization/update/<int:organization_id>', views.update_organization, name='update_organization'),
    path('organization/delete/<int:organization_id>', views.delete_organization, name='delete_organization'),
    path('unit/list/', views.unit_list, name='unit'),
    path('unit/list/create', views.create_unit, name='create_unit'),
    path('unit/list-and-create/update/<int:unit_id>/', views.update_unit, name='update_unit'),
    path('unit/list-and-create/delete/<int:unit_id>/', views.delete_unit, name='delete_unit'),
    path('create_election/', views.create_election, name='create_election'),
    path('elections/', views.election_list, name='elections'),
    path('elections/aspirant_signup/<int:election_id>/', views.aspirant_signup, name='aspirant_signup'),
    path('elections/voter_signup/<int:election_id>/', views.voter_signup, name='voter_signup'),
    path('elections/update/<int:election_id>/', views.update_election, name='update_election'),
    path('elections/delete/<int:election_id>/', views.delete_election, name='delete_election'),
    path('elections/position/<int:election_id>/', views.position_list, name='position'),
    path('elections/election/<int:election_id>/vote/', views.vote_view, name='vote_view'),
    path('elections/election/accreditions/aspirant/<int:election_id>', views.admin_aspirant, name='admin_aspirant'),
    path('elections/election/accreditions/voters/<int:election_id>', views.admin_voter, name='admin_voter'),
    path('approve_aspirants/<int:election_id>', views.approve_aspirants, name='approve_aspirants'),
    path('approve_voters/<int:election_id>', views.approve_voters, name='approve_voters'),
    path('get_aspirant_details/', views.get_aspirant_details, name='get_aspirant_details'),
    path('elections/election/vote/<int:election_id>/results/', views.election_results, name='election_results'),
    path('elections/election/vote/result/pdf/<int:election_id>', views.generate_pdf, name='generate_pdf')
]

    # path('detail/<int:organization_id>/', views.organization_detail, name='organization_detail'),

election/models.py
from django.db import models
from django.utils import timezone
from voteme.users.models import User

class Organization(models.Model):
    """Model definition for Organization."""
    """will riqure another model for obtaining users that can see an initiated election"""
    """user that create an organization will be default be part of it"""
    name = models.CharField( max_length=50)
    industry = models.CharField(max_length=50, help_text='software, union, government,construction...')
    description = models.CharField(max_length=50)
    address = models.CharField(max_length=50)
    contact = models.CharField(max_length=50)
    membership_size = models.IntegerField(help_text='help for counter overvotting, can be updated if neccessary')
    create_by =  models.ForeignKey(User, on_delete=models.CASCADE, blank=True, null=True)

    class Meta:
        """Meta definition for Organization."""

        verbose_name = 'Organization'
        verbose_name_plural = 'Organizations'

    def __str__(self):
        """Unicode representation of Organization."""
        return str(self.name)


class Unit_department(models.Model):
    """Model definition for Unit_department."""
    """for identifying range of voters in an organization"""
    title = models.CharField(max_length=50)
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE,null=True,default=None ,related_name='organization_units')

    class Meta:
        """Meta definition for Unit_department."""
        verbose_name = 'Unit_department'
        verbose_name_plural = 'Unit_departments'

    def __str__(self):
        """Unicode representation of Unit_department."""
        return str(self.title)
    # def save(self, *args, **kwargs):
    #     if not self.id:
    #         # If the instance is being created (not yet saved to the database)
    #         # Set the default title as "all"
    #         self.title = "all"
    #     super(Unit_department, self).save(*args, **kwargs)


class UserOrganization(models.Model):
    """Model definition for UserOrganization."""
    member = models.ForeignKey(to=User, on_delete=models.CASCADE)
    organization  = models.ForeignKey(to=Organization,null=True ,on_delete=models.CASCADE)
    class Meta:
        """Meta definition for UserOrganization."""

        verbose_name = 'UserOrganization'
        verbose_name_plural = 'UserOrganizations'

    def __str__(self):
        """Unicode representation of UserOrganization."""
        return str(self.member.email)


class Election(models.Model):
    """Model definition for Election."""
    title = models.CharField(max_length=50, blank=True)
    organization = models.ForeignKey(to=Organization, null=True ,on_delete=models.CASCADE, related_name='ElectionOrganization')
    department = models.ForeignKey(to=Unit_department, null=True ,on_delete=models.CASCADE, related_name='ElectionDepartment')
    start_date = models.DateField(blank=True)
    end_date = models.DateField(blank=True)
    aspirant_start = models.BooleanField(default=False)
    approved_all_contestant = models.BooleanField(default=False)
    voting_start = models.BooleanField(default=False)
    voting_end = models.BooleanField(default=False)

    class Meta:
        """Meta definition for Election."""

        verbose_name = 'Election'
        verbose_name_plural = 'Elections'

    def __str__(self):
        """Unicode representation of Election."""
        return str('{}{}'.format(self.organization, self.title))

    

class Position(models.Model):
    title = models.CharField(max_length=50)
    department = models.ForeignKey(Unit_department, on_delete=models.CASCADE, related_name='positions')
    election = models.ForeignKey(Election, on_delete=models.CASCADE, related_name='positions', null=True, blank=True)
    num_of_contestant = models.IntegerField(default=0, blank=True)

    def __str__(self):
        return self.title


class Aspirant(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=50, blank=True, default="default name")
    position = models.ForeignKey(Position, on_delete=models.CASCADE, related_name='aspirants')
    election = models.ForeignKey(Election, on_delete=models.CASCADE, related_name='aspirants')
    withdrawn = models.BooleanField(default=False)
    picture = models.ImageField(upload_to='aspirant_pictures/', null=True, blank=True)
    manifesto = models.TextField()
    registered_at = models.DateTimeField(default=timezone.now)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.user} - {self.position} ({self.election})"
    
    class Meta:
        unique_together = ('user', 'election')
        


class Voter(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    election = models.ForeignKey('Election', on_delete=models.CASCADE)
    organization_id = models.CharField( max_length=15)
    registered_at = models.DateTimeField(default=timezone.now)
    approved = models.BooleanField(default=False)

    def __str__(self):
        return self.user.email
    class Meta:
        unique_together = ('user', 'election', 'organization_id')


class Vote(models.Model):
    voter = models.ForeignKey (Voter, on_delete=models.CASCADE)
    election = models.ForeignKey(Election, on_delete=models.CASCADE)
    position = models.ForeignKey(Position, on_delete=models.CASCADE)
    aspirant = models.ForeignKey(Aspirant, on_delete=models.CASCADE)

    class Meta:
        unique_together = ('voter', 'position', 'election')  # To ensure a user can only vote once per position in an election

    def __str__(self):
        return f"Vote by {self.voter.user} for {self.position} in {self.election}"

election/forms.py
from django import forms
from django.contrib.auth import get_user_model
from .models import Organization, Unit_department,UserOrganization, Election, Position, Voter


class OrganizationForm(forms.ModelForm):
    class Meta:
        model = Organization
        exclude = ['create_by']


class Unit_departmentForm(forms.ModelForm):
    """Unit_departmentForm definition."""
    class Meta:
        model = Unit_department
        fields = '__all__'
    # def __init__(self, *args,**kwargs):
    #     # user_organizations = kwargs.pop('user_organizations', None)
    #     super(Unit_departmentForm, self).__init__(*args, **kwargs)
    #     user = get_user_model()
    #     if user:
    #         user_organizations = UserOrganization.objects.filter(member=user)
    #         organizations = [user_org.organization for user_org in user_organizations]
    #         if user_organizations:
    #             self.fields['organization'].queryset = organizations



class ElectionFormStage1(forms.ModelForm):
    class Meta:
        model= Election
        fields = '__all__'


class ElectionUpdateForm(forms.ModelForm):
    class Meta:
        model = Election
        fields = ['title', 'start_date', 'end_date', 'aspirant_start', 'approved_all_contestant', 'voting_start', 'voting_end']
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        # Set required attribute to False for each form field
        for field_name in self.fields:
            self.fields[field_name].required = False


class PositionForm(forms.ModelForm):
    """Form definition for Position."""

    class Meta:
        """Meta definition for Positionform."""

        model = Position
        exclude = ['election']

class VoterRegistrationForm(forms.ModelForm):
    class Meta:
        model = Voter
        fields = ['organization_id']

election/templates/admin_aspirant.html
{% extends "layoutss/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
Approve Aspirants
{% endblock title %}

{% block content %}
<div class="content">
    <div class="col-md-12">
        <h2 class="text-primary">Approve Aspirant for {{ election.title }} Election</h2>
    </div>
</div>
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-inline">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-5">
                            <h2 class="h1 badge-primary">Aspirants</h2>
                            <p class="text-danger font-italic mb-4 h3">
                                <span class="">Click aspirants name to display Aspirant's portfolio</span>
                            </p>

                            <!-- Add the form for approving aspirants here -->
                            <form method="post" action="{% url 'approve_aspirants' election.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary mb-3">Approve Selected Aspirants</button>

                                <ul class="list-group list-group-flush" id="aspirants-list">
                                    {% for aspirant in aspirants %}
                                    <li class="list-inline-item text-black-50 mt-3" data-aspirant-id="{{ aspirant.id }}">
                                        <input type="checkbox" name="aspirants_to_approve" value="{{ aspirant.id }}">
                                        <a href="#" class="aspirant-link" data-aspirant-id="{{ aspirant.id }}">
                                            {{ aspirant.name }}
                                        </a>
                                        <p class="d-inline-block">for post: {{ aspirant.position }}</p>
                                        
                                        {% if aspirant.approved %}
                                            <p class="badge badge-warning d-inline-block">Approved</p>       
                                        {% endif %}
                                            
                                    </li>
                                    {% endfor %}
                                    <!-- This will be dynamically updated by JavaScript -->
                                </ul>
                            </form>
                        </div>
                        <div class="col-md-6">
                            <!-- Details Column -->
                            <p class="text-primary h3 badge-secondary">Aspirant Portfolio</p>
                            <div id="aspirant-details">
                                <!-- Details of the selected aspirant will be displayed here -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

{% block javascripts %}
<script>
    // JavaScript code for handling aspirant details display
    const aspirantLinks = document.querySelectorAll(".aspirant-link");
    const detailsColumn = document.getElementById("aspirant-details");

    aspirantLinks.forEach(link => {
        link.addEventListener("click", function (event) {
            event.preventDefault(); // Prevent the default link behavior
            const selectedAspirantId = link.getAttribute("data-aspirant-id");

            // Create an XMLHttpRequest object
            const xhr = new XMLHttpRequest();

            // Define the URL for fetching aspirant details
            const url = "{% url 'get_aspirant_details' %}?aspirant_id=" + selectedAspirantId;

            xhr.open("GET", url, true);

            // Set up the callback function to handle the response
            xhr.onreadystatechange = function () {
                if (xhr.readyState === XMLHttpRequest.DONE) {
                    if (xhr.status === 200) {
                        const data = JSON.parse(xhr.responseText);

                        // Create an HTML template for displaying aspirant details
                        const detailsHTML = `
                            <div class="text-center">
                                <img src="${data.photo_url}" alt="${data.name}'s Photo" width="200">
                                <h3>${data.name}</h3>
                            </div>
                            <p class="offset-2">Position: ${data.position}</p>
                            <p class="offset-2 text-justify">Manifesto: ${data.manifesto}</p>
                        `;

                        // Display the aspirant details
                        detailsColumn.innerHTML = detailsHTML;
                    } else {
                        console.error("Error fetching aspirant details. Status: " + xhr.status);
                    }
                }
            };

            // Send the request
            xhr.send();
        });
    });
</script>
{% endblock javascripts %}

election/templates/admin_voter.html
{% extends "layoutss/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
Approve Voters
{% endblock title %}

{% block content %}
<div class="content">
    <div class="col-md-12">
        <h2 class="text-primary">Approve Voters for {{ election.title }} Election</h2>
    </div>
</div>
<div class="content">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-inline">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-5">
                            <h2 class="h1">Voters</h2>
                            

                            <!-- Add the form for approving aspirants here -->
                            <form method="post" action="{% url 'approve_voters' election.id %}">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-primary mb-3">Approve Selected Voters</button>

                                <ul class="list-group list-group-flush" id="aspirants-list">
                                    {% for voter in voters %}
                                    <li class="list-inline-item text-black-50 mt-3" data-aspirant-id="{{ voter.id }}">
                                        <input type="checkbox" name="voters_to_approve" value="{{ voter.id }}">
                                        
                                        <p class="d-inline-block"> {{ aspirant.election_id }}| {{voter.user.email}}</p>
                                        
                                        {% if voter.approved %}
                                            <p class="badge badge-warning d-inline-block">Approved</p>       
                                        {% endif %}
                                            
                                    </li>
                                    {% endfor %}
                                    <!-- This will be dynamically updated by JavaScript -->
                                </ul>
                            </form>
                        </div>
                        <div class="col-md-6">
                                                        
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

election/templates/position.html
{% extends "layoutss/base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}
  Positions
{% endblock title %}
{% block content %}
<style>
    .pt-1 {
    background-image: url({% static '' %}); /* Replace with your image file path */
    background-size: cover; /* Adjust how the image covers the body */
    background-repeat: no-repeat; /* Prevent the image from repeating */
    background-attachment: fixed; /* Keep the background fixed while scrolling */
}

</style>
<div class="content">
    <div class="row pt-1" style="height: 100vh;">
        <div class="col-md-6">
            <div class="">
                <div class="">
                    <h1 class="text-danger font-italic mt-5 mb-0">Election Posts(offices)</h1>
                </div>
                <div class="card-body">
                    <br>
                    <!-- Dropdown button for create -->
                    <div class="dropdown">
                        <button class="btn btn-primary bg-gradient-dark mb-2 dropdown-toggle" type="button"
                                id="createNewOrganizationDropdown" data-toggle="dropdown" aria-haspopup="true"
                                aria-expanded="false">
                            Add new post/office
                        </button>
                        <div class="dropdown-menu" aria-labelledby="createNewOrganizationDropdown">
                            <form class="px-4 py-3" action= "{% url 'position' election_id %}" method="post">
                                {% csrf_token %}
                                <div class="form-group">
                                    {{ form.title.label_tag }}
                                    {{ form.title }}
                                </div>
                                <div class="form-group">
                                    <label for="id_department">Select a department</label>
                                    <select name="department" id="id_department" class="form-control">
                                        <option value="">Select a department</option>
                                    </select>
                                </div>
                                <button type="submit" class="btn btn-primary">Add</button>
                            </form>
                        </div>
                    </div>

                    
                    <div class="table mt-0">
                        <table class="table tablesorter">
                            <thead>
                                <tr><th >Title</th><th>Department</th></tr>
                            </thead>
                            <tbody>
                                {% for position in positions %}
                                  <tr>
                                    <td class="font-weight-bolder">{{position.title}}</td>
                                    <td class="font-weight-bolder"> {{position.department}} </td>
                                  </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>

            </div>
        </div>
        
    </div>
</div>


{% endblock content %}

{% block javascripts %}
<script>
    var departmentData = {{ department| safe }};
    var departmentSelect = document.getElementById("id_department");

    departmentData.forEach(function (dept) {
        var option = document.createElement("option");
        option.value = dept.id;
        option.text = dept.title;
        departmentSelect.appendChild(option);
    });
</script>

{% endblock javascripts %}

{% for organization in organizations %}
<div class="modal fade" id="updateModal{{ organization.id }}" tabindex="-1" role="dialog"
    aria-labelledby="updateModal{{ organization.id }}Label" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="updateModal{{ organization.id }}Label">Update
                    Organization</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <form action="{% url 'update_organization' organization.id %}" method="post">
                    {% csrf_token %}
                    <div>
                        <label for="{{ form.name.id_for_label }}">Name:</label>
                        <input type="text" id="{{ form.name.id_for_label }}" name="{{ form.name.name }}"
                            value="{{ organization.name }}">
                    </div>
                    <div>
                        <label for="{{ form.industry.id_for_label }}">Industry:</label>
                        <input type="text" id="{{ form.industry.id_for_label }}" name="{{ form.industry.name }}"
                            value="{{ organization.industry }}">
                    </div>
                    <div>
                        <label for="{{ form.description.id_for_label }}">Description:</label>
                        <textarea id="{{ form.description.id_for_label }}"
                            name="{{ form.description.name }}">{{ organization.description }}</textarea>
                    </div>
                    <div>
                        <label for="{{ form.address.id_for_label }}">Address:</label>
                        <input type="text" id="{{ form.address.id_for_label }}" name="{{ form.address.name }}"
                            value="{{ organization.address }}">
                    </div>
                    <div>
                        <label for="{{ form.contact.id_for_label }}">Contact:</label>
                        <input type="text" id="{{ form.contact.id_for_label }}" name="{{ form.contact.name }}"
                            value="{{ organization.contact }}">
                    </div>
                    <div>
                        <label for="{{ form.membership_size.id_for_label }}">Membership
                            Size:</label>
                        <input type="number" id="{{ form.membership_size.id_for_label }}"
                            name="{{ form.membership_size.name }}" value="{{ organization.membership_size }}">
                    </div>
                    <button type="submit" class="btn btn-primary">Save</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endfor %}

<!-- Delete Modal -->
{% for organization in organizations %}
<div class="modal fade" id="deleteModal{{ organization.id }}" tabindex="-1" role="dialog"
    aria-labelledby="deleteModal{{ organization.id }}Label" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="deleteModal{{ organization.id }}Label">Confirm Delete
                    Organization</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to delete the organization "{{ organization.name }}"?</p>
            </div>
            <div class="modal-footer">
                <form action="{% url 'delete_organization' organization.id %}" method="post">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-danger">Delete</button>
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                </form>
            </div>
        </div>
    </div>
</div>
{% endfor %}

election/templates/vote_view.html
{% extends "layoutss/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
Cast Vote
{% endblock title %}

{% block content %}
<div class="content">
    <div class="container">
        <div class="row">
            <h2>Make your choice now, by vote your favorite candidate</h2>
        </div>
        <div >
            <a class="btn btn-danger mb-3" href="{% url 'election_results' election.id %}">View Election Result</a>

        </div>
        <div class="row">
            {% for aspirant in aspirants %}
            <div class="col-md-4">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-primary mb-0">Vote!</h3>
                    </div>
                    <div class="card-body offset-md-2">
                        {% if aspirant.picture %}
                        <img src="{{ aspirant.picture.url }}" alt="{{ aspirant.name }}" width="150"
                            class="shadow-md-4 p-2">
                        {% endif %}
                        <h4 class="fs-5 mb-1 fw-bold">{{ aspirant.name }}</h4>
                        <h6 class="fs-7">Running to Be: <span class="text-primary fw-bold">{{ aspirant.position }}</span></h6>
                        <form method="post" action="{% url 'vote_view' election.id %}">
                            {% csrf_token %}
                            <input type="hidden" name="position_id" value="{{ aspirant.position.id }}">
                            <input type="hidden" name="aspirant_id" value="{{ aspirant.id }}">
                            <button type="submit" class="btn btn-primary">Vote</button>
                        </form>
                    </div>
                </div>
            </div>
            {% if forloop.counter|divisibleby:3 and not forloop.last %}
            </div>
            <div class="row">
            {% endif %}
            {% endfor %}
        </div>
    </div>
</div>
{% endblock content %}

election/templates/voter_signup.html
<!-- voter_signup.html -->

{% extends "layoutss/base.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
  Join Voter
{% endblock title %}
{% block content %}
  <h1>Voter Registration for {{ election.title }} Election</h1>
  <div class="col-md-5">
    <form method="post">
      {% csrf_token %}
      {{ form|crispy }}
      <button type="submit" class="btn btn-primary">Register</button>
    </form>
  </div>
{% endblock %}